version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/kotlin"
    schedule:
      interval: "monthly"
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "monthly"
