version: '3.8'

services:
  database:
    build: database
    environment:
      POSTGRES_DB: handson
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - published: 5432
        target: 5432
