changelogFile: src/main/resources/db/changelog/db.changelog-master.yaml
# changelogFile: /db/changelog/db.changelog-master.yaml
# changelogDirectory: /src/main/resources
driver: org.postgresql.Driver
logLevel=debug
url=jdbc:postgresql://localhost:5432/handson
user=user
username=user
password=user123
