name: Kotlin

on:
  push:
    paths: kotlin/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Make Gradle executable
        run: chmod +x gradlew
        working-directory: ./kotlin
      - name: Run tests with Gradle
        run: ./gradlew test
        working-directory: kotlin
